config/routes.rb
SampleApp::Application.routes.draw do

  resources :sessions, :only => [:new, :create, :destroy]
  resources :users do
    member do
      get :archive
      get :general_settings
      get :ebay_settings
      get :subscribe_settings
    end
  end
  resources :ebay_users, :only => [:new, :create, :destroy] do
       collection do
         get 'complete'
       end
  end
  resources :orders, :only => [:new, :edit, :update, :create, :destroy] do
    member do
      get :complete
    end
  end
  resources :forgot, :only => [:new, :show, :create, :update]
  resource :inbox, :controller => 'inbox', :only => [:show,:create]
  resource :track_updates, :controller => 'track_updates', :only => [:show,:create]
  resources :subscribers, :only => [:create] do
    member do
      get :unsubscribe
    end
  end

  root :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/news', :to => 'pages#news'
  match '/terms', :to => 'pages#terms'
  match '/android_app', :to => 'pages#android_app'
  match '/ios_app', :to => 'pages#ios_app'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signin_lightbox', :to => 'sessions#new_lightbox'
  match '/signout', :to => 'sessions#destroy'
  match '/beta_thank_you', :to => 'pages#beta_thank_you'
  match 'bookmarklet_explain', :to => 'pages#bookmarklet_explain'

  match '/orders/save_order', :to => 'orders#save_order'
  match '/orders/order_saved', :to => 'orders#order_saved_msg'
  match '/orders/order_saved_chrome_ext', :to => 'orders#order_saved_msg_chrome_ext'
  match '/chrome_ext', :to => "pages#chrome_ext"
  match '/.well-known/acme-challenge/*pass', :to => "pages#letsencrypt_check"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                        :integer          not null, primary key
#  name                      :string(255)
#  email                     :string(255)
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  encrypted_password        :string(255)
#  salt                      :string(255)
#  admin                     :boolean          default(FALSE)
#  orders_notifications      :boolean          default(TRUE)
#  messages_notifications    :boolean          default(TRUE)
#  unsubscribe_leading_mail  :text
#  referer                   :text             default("none")
#  allow_tracking_info       :boolean          default(FALSE)
#  default_days_notification :integer
#

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :email, :name,  :password, :password_confirmation, :admin, 
                  :messages_notifications, :orders_notifications, :referer, :default_days_notification
  @email_regex = /\A[\w\+\-.]+@([\da-zA-Z\-.])*[\.]([a-zA-Z\..])+\z/i

  has_and_belongs_to_many :user_mails
  has_many :orders,     :dependent => :destroy
  has_many :ebay_users, :dependent => :destroy
  has_one  :forgot_key, :dependent => :destroy

  validates :name,  :presence => true,
            :length => { :maximum => 50 }

  validates :email, :presence => true,
                    :format   => { :with => @email_regex},
                    :uniqueness => { :case_sensitive => false }

  validates :password, :presence => true,
                      :confirmation => true,
                      :length => { :within => 4..40 }

  before_save :encrypt_password

  def User.email_regexp
    @email_regex
  end

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def is_admin?
    found_user = User.find(id)
    found_user.admin unless found_user.nil?
  end

  def feed
    Order.live_orders(User.find_by_id(id))
  end

  def archive_feed
    Order.archive_orders(User.find_by_id(id))
  end

  def User.authenticate(email, password)
    user = find_by_email(email)
    (user && user.has_password?(password)) ? user : nil
  end

  def User.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  def get_default_days_notification_value
    self.default_days_notification
  end

  private

  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end

  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(password) # self is not necessary on the "password" but it is necessary on the
                                                # start line because elsewise it will create a local variable */
  end

  def make_salt
    secure_hash("#{Time.now.utc}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
end

app/controllers/users_controller.rb
require 'ebay/api/ebay_api_main'

class UsersController < ApplicationController
  include ApplicationHelper

  before_filter :authenticate, :except => [:new, :create]
  before_filter :correct_user, :only => [:edit, :update, :general_settings, :ebay_settings, :subscribe_settings]
  before_filter :admin_only,   :only => :destroy

  def index
    if !current_user.admin?
      @user  = current_user
      render 'public/404'
    else
      @users = User.paginate(:page => params[:page])
      @user  = current_user
      @title = "All users"
    end

  end
  def show

    #if signed_in?
      @user = current_user
      @title = @user.name
      @feed_items = @user.feed.paginate(:page => params[:page])
      if current_user != User.find(params[:id])
          flash.now[:error] = "Access denied"
          render 'show'
      end
    #else
    #  redirect_to root_path
    #end

  end


  def new
    if signed_in?
      @user = current_user
      @title = @user.name
      flash[:error] = "You are already signed up...."
      redirect_to @user

    else
      collect_referer
      @user = User.new
      @title = "Sign Up"
    end
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      UserMailer.welcome_email(@user).deliver
      flash[:success] = "Welcome to the Order Tracking app"
      sign_in_first_time(@user)
      redirect_to @user # possible user_path(@user) also
    else
      @title = "Sign Up"
      render 'new'
    end
  end

  def edit
      @title = "Edit user"
      @user  = current_user
  end

  def update

    #check old password and remove old_password param
    if !@user.has_password?(params[:user][:old_password])
      flash.now[:error] = "Wrong old password"
      @title = "Edit user"
      if subscribe_settings_context(params)
        render 'subscribe_settings'
      else
      #  general settings context
        render 'general_settings'
      end
      return
    end

    params[:user].delete(:update_user_context)

    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user][:password]              = params[:user][:old_password]
      params[:user][:password_confirmation] = params[:user][:old_password]
    end

    params[:user].delete(:old_password)

    if @user.update_attributes(params[:user])
      flash[:success] = "User saved successfuly"
      redirect_to @user # possible user_path(@user) also
    else
      flash[:error] = "Error in user saving"
      @title = "Edit user"
      render 'edit'
    end

  end

  def destroy
      user = User.find(params[:id])
      if !currect_user?(user)
        user.destroy
        redirect_to users_path, :flash => { :success => "User successfully deleted" }
      else
        redirect_to users_path, :flash => { :error => "An admin can't delete itself" }
      end
  end

  def archive
    @archive_mode = true
    @user = current_user
    @title = @user.name
    @feed_items = @user.archive_feed.paginate(:page => params[:page])
    if current_user != User.find(params[:id])
      flash.now[:error] = "Access denied"
    end

    render 'show'
  end

  def ebay_settings
    if signed_in?
      @user = current_user
      @title = "eBay settings"
      @ebay_accounts = @user.ebay_users
    end
  end

  def general_settings
    @user = current_user
    @title = "General settings"
  end

  def subscribe_settings
    @unsubscribe_mail = params[:mail]
    @user = current_user
    @title = "Subscribe settings"
  end

  private

    def correct_user
      @user = User.find(params[:id])

      if current_user != nil && !currect_user?(@user)
        flash[:error] = "Access denied"
        redirect_to(root_path)
      end
    end

    def admin_only
      redirect_to(root_path) unless current_user.admin?
    end

    def subscribe_settings_context(params)
      context = params[:user][:update_user_context]
      context != nil && context == 'subscribe'
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def userNameMaxLength
    50
  end

  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options.merge!(:secure => true))
  end

  def update_user_attrs(user, name, email, pass, pass_conf)
    user.name = name
    user.email = email
    user.password = pass
    user.password_confirmation = pass_conf
    return user
  end
end

app/views/users/_ebay_account.html.erb
<tr>
  <td class='ebay_nickname'>
    <%= ebay_account.name %>
  </td>
  <td class='ebay_expiration'>
    <%= ebay_account.expiration %>
  </td>
  <td class='delete_ebay_account'>
    <%= link_to "", ebay_user_path(ebay_account),
                :method => :delete,
                :data => { :confirm => "You sure?" },
                :class => "foundicon-trash brown",
                :title => "Delete #{ebay_account.name}" %>
  </td>
</tr>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<div class="field">
  <!--<%= f.label :name %>-->
  <%= f.text_field :name,
                   :placeholder => 'Name',
                   'ng-init' => "name = '#{@user ? @user.name : ''}';",
                   'ng-model' => 'name',
                   'ng-required' => 'true' %>
</div>

<%= render 'shared/fields_mail_and_pass', :f => f, :require_password => ((defined? require_password) != nil) ? require_password : nil %>

app/views/users/_user.html.erb
<li>
  <p> <%= gravatar_for user, :size => 30 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? %>
  |
  <%= link_to "Delete", user_path(user), :method => :delete, :data => { :confirm => "You sure?" },
                                                             :title => "Delete #{user.name}" %>
  <% end %>
  <p/>
</li>

app/views/users/ebay_settings.html.erb
<h3 align=center>
  eBay Accounts
</h3>
<br />

<div class='text-center'>
    <%= link_to "Add eBay Account", new_ebay_user_path(@user), :class => 'button' %>
</div>
<br />
<% if @ebay_accounts.any? %>
    <div align=center>
      <h4>Existing accounts</h4>
      <br />
        <table class="ebay_accounts text-center" summery="eBay accounts">
          <thead>
          <tr>
            <th class="text-center">
              Account Nickname
            </th>
            <th class="text-center">
              Updates expiration
            </th>
            <th></th>
          </tr>
          </thead>
          <%= render :partial => 'users/ebay_account', :collection => @ebay_accounts %>
        </table>
    </div>

<% else %>
    <h4 align=center>No accounts attached yet</h4>
<% end %>

app/views/users/edit.html.erb
<h3 align="center">Edit user</h3>

<div class='text-center small-12 medium-6 large-6 row'>
  <%= link_to "General Settings", general_settings_user_path(current_user), :class => 'button expand' %>
  <br />
  <%= link_to "Subscribe Settings", subscribe_settings_user_path(current_user), :class => 'button expand' %>
  <br />
  <%= link_to "Ebay Settings", ebay_settings_user_path(current_user), :class => 'button expand' %>

</div>

app/views/users/general_settings.html.erb
<%= form_for(@user) do |f| %>

    <div class="small-11 medium-6 large-4 row">
      <br />
      <div class="field">
        <!--<%= f.label 'Old password' %>-->
        <%= f.password_field :old_password, :placeholder => 'Password',
                       'ng-model' => 'old_pass',
                       'ng-required' => 'true' %>
      </div>

      <%= render 'users/fields', :f => f, :require_password => false %>

      <div class="field">
        <% default_days_text = "Default number of days for order notification" %>
        <%= f.text_field :default_days_notification,
                   :title => default_days_text,
                   :placeholder => default_days_text,
                   'ng-init' => "default_days_notification = '#{@user.default_days_notification ? @user.default_days_notification : ''}';", 
                   'ng-model' => 'default_days_notification' %>
      </div>

      <div>
        <%= gravatar_for User.find(@user) %>
        <a href="http://gravatar.com/emails" target=_blank>change</a>
      </div>

      <div class="action" align="center">
        <%= f.submit "Update", :class => "button [tiny small large]" %><br />
      </div>
    </div>
<% end %>

app/views/users/index.html.erb
<h1>All users</h1>

<%= foundation_paginate @users %>

<ul class="users">
  <% @users.each do |user| %>
     <%= render 'user', :user => user, :current => @user %>
  <% end %>

</ul>

<%= foundation_paginate @users %>

app/views/users/new.html.erb
<% if @signup_disabled %>
<br /><h3 class='brown center'>Currently Sign up isn't available</h3><br />
  <h4 class='brown center'><strong>subscribe NOW</strong> on the <%= link_to "main page", root_path %> and you'll get notified once the site is open</h4>
<% else %>
<h3 class='brown center'>Sign up</h3>
<div class="large-4 medium-4 small-12 row">
  <!--<div class="row">-->
    <%= form_for(@user, :html => {:name => 'signup'}) do |f| %>
      <div class='horizontal-center'>
        <%= render 'users/fields', :f => f %>
        <%= f.hidden_field :referer, :value => cookie_fetch_referer %>
        By signing up you agree with the <%= link_to 'Terms of use', terms_path, :target => "_blank" %>
        <div class="field center">
          <br /><br /><%= f.submit "Sign up", :class => 'button' %><br />
        </div>
      </div>
    <% end %>
  <!--</div>-->
</div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <div class='row'>
    <div class='small-12 medium-12 large-12'>
      <tr>
        <div class='small-12 medium-10 large-10 columns'>
            <td class="main">
              <%= render 'shared/mobile_apps' %>
              <%= render 'shared/feed' %>
            </td>
        </div>

      </tr>
    </div>
  </div>

</table>

app/views/users/subscribe_settings.html.erb
<h3 align="center">Notifications Settings</h3>

<%= form_for(@user) do |f| %>

    <div class="small-11 medium-4 large-4 row">
      <br />

      <div class="center field small-12 columns">
        <%= f.check_box :messages_notifications %>
        <%= f.label :messages_notifications %><br />
        <p class="unsubscribe-explain-text">Including announcements of new features, changes in the site, etc.</p><br />
      </div>

      <div class="center field small-12 columns">
        <%= f.check_box :orders_notifications %>
        <%= f.label :orders_notifications %><br />
        <p class="unsubscribe-explain-text">Including order tracking updates, adding orders notifications</p><br />
      </div>


      <div class="center field small-12 columns">
        <!--<%= f.label 'Old password' %>-->
        <%= f.password_field :old_password, :placeholder => 'Password' %><br />
      </div>

      <% if @unsubscribe_mail != nil %>
        <%= f.hidden_field :unsubscribe_leading_mail, :value => @unsubscribe_mail %>
      <% end %>
      <%= f.hidden_field :update_user_context, :value => 'subscribe' %>

      <div class="action" align="center">
        <br /><%= f.submit "Update", :class => "button [tiny small large]" %><br />
      </div>
    </div>
<% end %>