config/routes.rb
SampleApp::Application.routes.draw do

  resources :sessions, :only => [:new, :create, :destroy]
  resources :users do
    member do
      get :archive
      get :general_settings
      get :ebay_settings
      get :subscribe_settings
    end
  end
  resources :ebay_users, :only => [:new, :create, :destroy] do
       collection do
         get 'complete'
       end
  end
  resources :orders, :only => [:new, :edit, :update, :create, :destroy] do
    member do
      get :complete
    end
  end
  resources :forgot, :only => [:new, :show, :create, :update]
  resource :inbox, :controller => 'inbox', :only => [:show,:create]
  resource :track_updates, :controller => 'track_updates', :only => [:show,:create]
  resources :subscribers, :only => [:create] do
    member do
      get :unsubscribe
    end
  end

  root :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/news', :to => 'pages#news'
  match '/terms', :to => 'pages#terms'
  match '/android_app', :to => 'pages#android_app'
  match '/ios_app', :to => 'pages#ios_app'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signin_lightbox', :to => 'sessions#new_lightbox'
  match '/signout', :to => 'sessions#destroy'
  match '/beta_thank_you', :to => 'pages#beta_thank_you'
  match 'bookmarklet_explain', :to => 'pages#bookmarklet_explain'

  match '/orders/save_order', :to => 'orders#save_order'
  match '/orders/order_saved', :to => 'orders#order_saved_msg'
  match '/orders/order_saved_chrome_ext', :to => 'orders#order_saved_msg_chrome_ext'
  match '/chrome_ext', :to => "pages#chrome_ext"
  match '/.well-known/acme-challenge/*pass', :to => "pages#letsencrypt_check"

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(object.errors.count, "error") %>
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> from being saved:
      </h2>
      <p>There were problems with the following fields:</p>
      <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>

    </div>

<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>

    <% if !@archive_mode %>
        <div class='small-12 medium-6 large-6 row'>
          <h3><strong><%= link_to "New Order", new_order_path, :class => 'button expand' %></strong></h3>
        </div>
    <% end %>

    <div class='pagination-centered'>
    <%= foundation_paginate @feed_items %>
    </div>

    <table class="orders" summery="Status feed">
    <thead>
      <tr>
        <%= render 'orders/order_titles' %>
      </tr>
    </thead>
    <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
    </table>

    <div class='pagination-centered'>
        <%= foundation_paginate @feed_items %>
    </div>

<% else %>

    <h2 class='text-center'><em>
          <% if @archive_mode %>
            No orders in archive..
        <% else %>
            <div class='small-12 medium-6 large-6 row'>
              <h4>No orders YET.</h4><br />
              <strong class='brown'>Get started:</strong><br /><br />
              <%= link_to "Make a New Order", new_order_path, :class => 'button expand success' %><br />
              <%= link_to "Attach eBay account", ebay_settings_user_path, :class => 'button expand' %><br />
              <%= link_to "Meet our Bookmarklet", bookmarklet_explain_path, :class => 'button expand alert' %><br />
            </div>
        <% end %>

    </em></h2>

<% end %>

app/views/shared/_feed_item.html.erb
<tr>

      <% if currect_user?(feed_item.user) %>
      <%= render 'orders/order', :order => feed_item %>

      <td class="small-2 medium-1 large-1 column">
        <h3>
      <% if !@archive_mode %>

          <%= link_to "", "/orders/#{feed_item.id}/complete",
                      :title  => "Mark as Picked",
                      :class => "checkmark foundicon-checkmark brown" %><br />
        <!--</h3>-->
      <!--</td>-->
      <% end %>
      <!--<td class='small-1 medium-1 large-1 column'>-->
        <!--<h3>-->
          <%= link_to "", "/orders/#{feed_item.id}/edit", :title => "Edit",
                                                            :class => "foundicon-edit brown" %><br />
        <!--</h3>-->
      <!--</td>-->

      <!--<td class='small-1 medium-1 large-1 column'>-->
        <!--<h3>-->
          <%= link_to "", feed_item,
                                :method => :delete,
                                :data   => { :confirm => "Are you sure?" },
                                :title  => "Delete",
                                :class => "foundicon-trash brown" %>
        </h3>
      </td>
      <% end %>

</tr>

app/views/shared/_fields_mail_and_pass.html.erb
<div class="field email">
  <!--<%= f.label :email %>-->

  <%= f.email_field :email,
                   :placeholder => 'Email',
                   'ng-init' => "email = '#{@user ? @user.email : ''}';",
                   'ng-model' => 'email',
                   'ng-required' => 'true' %>
</div>

<div class="field password">
  <!--<%= f.label :password %>-->
  <% password_required = (((defined? require_password) != nil) ? require_password : nil) != false %>
  <%= f.password_field :password,
                       :placeholder => 'New password',
                       'ng-model' => 'pass',
                       'ng-minlength' => 4,
                       'ng-required' => password_required.to_s %>
  <small class="error" ng-show="signup['user[password]'].$dirty && signup['user[password]'].$error.minlength">
    Password should be 4 characters or more
  </small>

</div>

<div class="field confirmation">
  <!--<%= f.label :password_confirmation, "Confirmation" %>-->
  <%= f.password_field :password_confirmation,
                       :placeholder => 'Confirm',
                       'ng-model' => 'pass_conf',
                       'ng-class' => "{confirm_pass_invalid: signup['user[password_confirmation]'].$dirty == true && pass_conf != pass,
                                       confirm_pass_valid: signup['user[password_confirmation]'].$dirty && pass_conf == pass}",
                       'ng-required' => password_required.to_s %>

</div>

app/views/shared/_mobile_apps.html.erb
<div align=center class='logo'>
	<div class="hide-for-touch">
	  	<%= link_to android_app_logo_small, android_app_short, :target => "_blank" %>
  		<%= link_to ios_app_logo_small, ios_app_short, :target => "_blank" %>
  	</div>
</div>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <%= gravatar_for current_user, :size => 30 %>
    <span class="user_name">
      <%= current_user.name %><br />
    </span>

  </a>
</div>

app/views/shared/_user_order_stats.html.erb
<span class="user_orders">
      <strong>Orders</strong> <%= user.orders.size %><br />
</span>