config/routes.rb
SampleApp::Application.routes.draw do

  resources :sessions, :only => [:new, :create, :destroy]
  resources :users do
    member do
      get :archive
      get :general_settings
      get :ebay_settings
      get :subscribe_settings
    end
  end
  resources :ebay_users, :only => [:new, :create, :destroy] do
       collection do
         get 'complete'
       end
  end
  resources :orders, :only => [:new, :edit, :update, :create, :destroy] do
    member do
      get :complete
    end
  end
  resources :forgot, :only => [:new, :show, :create, :update]
  resource :inbox, :controller => 'inbox', :only => [:show,:create]
  resource :track_updates, :controller => 'track_updates', :only => [:show,:create]
  resources :subscribers, :only => [:create] do
    member do
      get :unsubscribe
    end
  end

  root :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/news', :to => 'pages#news'
  match '/terms', :to => 'pages#terms'
  match '/android_app', :to => 'pages#android_app'
  match '/ios_app', :to => 'pages#ios_app'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signin_lightbox', :to => 'sessions#new_lightbox'
  match '/signout', :to => 'sessions#destroy'
  match '/beta_thank_you', :to => 'pages#beta_thank_you'
  match 'bookmarklet_explain', :to => 'pages#bookmarklet_explain'

  match '/orders/save_order', :to => 'orders#save_order'
  match '/orders/order_saved', :to => 'orders#order_saved_msg'
  match '/orders/order_saved_chrome_ext', :to => 'orders#order_saved_msg_chrome_ext'
  match '/chrome_ext', :to => "pages#chrome_ext"
  match '/.well-known/acme-challenge/*pass', :to => "pages#letsencrypt_check"

end

app/views/pages/_beta_subscribe.html.erb
<div class='text-center'>
  <div class='small-10 medium-6 large-6 row'>
    <h1 class='brown'>
        <strong>Coming SOON!</strong>
    </h1>
    <h4 class="brown">
      <em>Sign up using the box below<br />
      Get notified once registration opens</em>
    </h4>
    <br />
  </div>
    <%= form_for Subscriber.new do |f| %>

      <div class="center field small-6 medium-4 large-3 row">
        <%= f.text_field :email, :placeholder => 'E-Mail' %><br />
        <%= f.submit "Subscribe NOW!", :class => 'button expand' %><br />
      </div>
    <% end %>
</div>

app/views/pages/about.html.erb
<div class='small-11 medium-8 large-6 row'>
    <h1 class='about-header brown'>This is what it all ABOUT!!!</h1>

    <p>
      Order Tracking is a solution for people who make orders (and who doesn't?!?).<br />

      Whether you're ordering product on the internet or over the phone,
      you can insert it to your wall and have an organized list of all your orders,
      details like when you bought them, what is the current status of them, etc.<br />

      Afraid to forget an order? need a reminder?<br />
      No problem!! You can set notification to be sent after X days has been passed since you purchased the product.<br /><br />


      Many features are on development and will make your order organizing and tracking even simpler!<br /><br />

      <strong><%= link_to "Sign up now!!", signup_path %></strong><br /><br />

      <em><strong>Order Tracking Stuff</strong></em><br /><br />
    </p>
</div>

app/views/pages/beta_thank_you.html.erb
<div class="small-10 medium-8 large-8 row">
    <h1 align=center class="brown">
      <strong>Thank U for subscribing <em>Order Tracking</em> beta list!</strong><hr>
    </h1>
    <br />
    <p align=center>
      A mail was sent to your E-mail address. please verify that you received it.<br />
      SOON you'll start to organize your orders more easily and effectively!<br /><br />
      In case you haven't got the mail in the next 10 minutes, please check the E-mail you've entered and correct it if necessary.<br />
      If you need any assistance in this step, please <%= link_to "contact", contact_path %> us.<br />
    </p>
</div>

app/views/pages/bookmarklet_explain.html.erb
<div class="medium-8 large-8 row">
  <h1 align=center class="brown">
    <strong><em>Order Tracking</em> Bookmarklet</strong></h1>
  <h3 align=center class="brown">A super easy way to add your orders!</h3>
  <hr>

  <br />
  <p>
    <strong>What is it exactly?</strong><br />
    a new and easy way to add your orders, even more convenient than before!<br /><br />
    <strong>How it works?</strong><br />
    1. Drag the <strong>button</strong> below to your bookmarks bar.<br />
    2. Any time you're in a page of a product you want to add, just click the new bookmark you've just dragged!<br />
    3. your order added to your account!<br /><br /></p>
  <p align=center>
    <% if Rails.env == 'production'
        site_addr = 'www.ordertrk.com'
    else
        site_addr = '127.0.0.1:3000'
    end %>

    <%= link_to "Add to Order Tracking", "javascript:(function(){  _my_script=document.createElement('SCRIPT');  _my_script.type='text/javascript';  _my_script.src='http://#{site_addr}/bookmarklet/order_tracking_bookmarklet.js';  document.getElementsByTagName('head')[0].appendChild(_my_script);})();", :class => 'button' %>


  </p>
</div>

app/views/pages/contact.html.erb
<div class='small-11 medium-8 large-6 row'>
	<h1>Contact us..</h1>
	<p>Mail for contacting <a href="mailto:info@ordertrk.com">info@ordertrk.com</a></p>
</div>

app/views/pages/help.html.erb
<div class='small-11 medium-10 large-8 row'>
  <h1 class='brown text-center'>Help...</h1>
    <h2>F.A.Q</h2>
    <p><strong>Q: How can i use the Chrome extension in the most easy way?</strong></br>
    A: First, you can copy the URL of the image of the product in advance, then select (mark) the price of the product and then click on the extention. The price form the selection will be automatically filled and you'll only have to paste the URL of the image. ENJOY the easyness!</p>

    <p><strong>Q: Can i set another notification after i got the first one?</strong></br>
    A: sure you can! just update the number of days in the edit menu of the order, and you'll get new notification</p>

    <p><strong>Q: Why can't i add order via my e-mail?</strong></br>
      A: You can send an e-mail with Paypal receipt to neworder@ordertrk.com.<br/>There are some things you need to check before you send a Paypal receipt:</br>
    1. check that the mail content is html (if you haven't changed this in Paypal preferences, it should be html.</br>
    2. check that the subject contains 'Paypal'</br>
    3. check that you're sending the mail from an e-mail address that registered in the site.</p>

    <p><strong>Q: How long after i make my purchase in eBay should i expect the order to appear in my <em>Order Trcking</em>
     account?</strong></br>
      A: The check for new buying is happening once every hour approximately, so you should expect the order to be
      added in less than a hour.</br>
    </p>

    <p><strong>Q: When I click on the browser plugin to add new order nothing happens, why is it?</strong></br>
      A: After check regular stuff (internet connectivity, etc.), check if the site you're on is HTTPS.</br>
      Currently the plugin (AKA 'bookmarklet') isn't supported on HTTPS sites. You can use the Chrome extension for HTTPS sites.
    </p><br/><br />
</div>

app/views/pages/home.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=214699361939893";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));

//    function like() {
//        console.log("page_like_subscribe");
//        FB.Event.subscribe('edge.create', page_like_cb);
//        console.log("page_like_after_subscribe");
//    }
//    var page_like_cb = function(url, html_element) {
////        html_element.height = "350px";
//        console.log("page_like_cb");
//        $(".fb-like").height(350);
//        console.log("page_like_cb_after_set");
//    }
</script>
<br />
<h1 align=center><strong>Welcome!!</strong></h1>
<h3 align=center>Organize your orders.<br /><strong>One place.</strong><br />From this day on.</h3>

<br />

<div align=center class='logo'>
  <%= link_to android_app_logo, android_app_url, :target => "_blank" %>
</div>
<br />

<div align=center class='logo'>
  <%= link_to ios_app_logo, ios_app_url, :target => "_blank" %>
</div>
<br />

<div align=center>
  <%= link_to "Sign Up Now!", signup_path, :class => "signup_button radius button" %>
</div>

<div align=center>
    <%= link_to "Already a member?", signin_path %>
</div>

<br /><br />

<div align=center class='logo'>
  <%= logo %>
</div>
 <br /><br />
<div align=center>
<div class="fb-like facebook_container text-center" data-href="https://www.facebook.com/ordertrk" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
</div>
<br />

app/views/pages/letsencrypt_check.text.erb
<enter string here>

app/views/pages/news.html.erb
<div class='small-11 medium-10 large-8 row'>
    <h1 class='brown text-center'>What's new??</h1>

    <p><strong><u>21/11/2015</u></strong></br>
    <p><strong>Order Tracking Chrome extension!</strong></br>
      Chrome extension is now available on the <em>Chrome Web Store</em>. It is an improvment comparing to the bookmarklet - it is easier to use and you can run it on HTTPS sites.</br>
      Download it <%= link_to "Here", chrome_ext_path %> and enjoy!</p>

    <p><strong><u>23/06/2015</u></strong></br>
    <p><strong>Order Tracking comes to AppStore also!</strong></br>
      We've finished to work on our <em>IOS</em> app and now <em>Apple's</em> products holders can use <em>Order Tracking</em> on their phones and tablets!</br>
      Download it <%= link_to "Here", ios_app_path %> and join the fun on iPhone and iPad!</p>

    <p><strong><u>18/12/2014</u></strong></br>
    <p><strong>Order Tracking Android app!</strong></br>
      We're glad to announce that our <em>Android</em> app is now live and kicking!</br>
      Download it <%= link_to "Here", android_app_path %> and enjoy the tracking on the move!</p>


    <p><strong><u>01/04/2014</u></strong></br>
    <p><strong>eBay integration!</strong></br>
      Starting today you can add <em>eBay</em> account to your <em>Order Tracking</em> Account!</br>
      After the simple adding, your orders from eBay will be added automatically and you'll receive updates about them!</br>
      See the settings menu for details.</br></p>

    <p><strong><u>11/01/2014</u></strong></br>
    <p>Automatic adding of orders via mail!</br>
      From now on you can add your orders simply!</br>
      Just forward your Paypal receipts to neworder@<%= UserMailer.site_url %> from your registered E-mail address
      and the order will wait for you inside your account! that SIMPLE!</p>

    <p><strong><u>17/12/2013</u></strong></br>
    <p>Notifications for orders are now available!</br>
    You can edit your orders or create a new ones and set reminder - see inside the order's details</p>
</div>