config/routes.rb
SampleApp::Application.routes.draw do

  resources :sessions, :only => [:new, :create, :destroy]
  resources :users do
    member do
      get :archive
      get :general_settings
      get :ebay_settings
      get :subscribe_settings
    end
  end
  resources :ebay_users, :only => [:new, :create, :destroy] do
       collection do
         get 'complete'
       end
  end
  resources :orders, :only => [:new, :edit, :update, :create, :destroy] do
    member do
      get :complete
    end
  end
  resources :forgot, :only => [:new, :show, :create, :update]
  resource :inbox, :controller => 'inbox', :only => [:show,:create]
  resource :track_updates, :controller => 'track_updates', :only => [:show,:create]
  resources :subscribers, :only => [:create] do
    member do
      get :unsubscribe
    end
  end

  root :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/news', :to => 'pages#news'
  match '/terms', :to => 'pages#terms'
  match '/android_app', :to => 'pages#android_app'
  match '/ios_app', :to => 'pages#ios_app'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signin_lightbox', :to => 'sessions#new_lightbox'
  match '/signout', :to => 'sessions#destroy'
  match '/beta_thank_you', :to => 'pages#beta_thank_you'
  match 'bookmarklet_explain', :to => 'pages#bookmarklet_explain'

  match '/orders/save_order', :to => 'orders#save_order'
  match '/orders/order_saved', :to => 'orders#order_saved_msg'
  match '/orders/order_saved_chrome_ext', :to => 'orders#order_saved_msg_chrome_ext'
  match '/chrome_ext', :to => "pages#chrome_ext"
  match '/.well-known/acme-challenge/*pass', :to => "pages#letsencrypt_check"

end

app/views/layouts/_footer.html.erb
<footer><br />

  <nav class="top-bar" data-topbar>
        <section class="top-bar-section">
            <!-- Right Nav Section -->
            <ul>
              <div class='small-12 medium-8 large-4 row full-width'>
                <% if signed_in? %>
                    <li class='text-center small-3 column'><%= link_to "About", about_path %></li>
                    <li class='text-center small-3 column'><%= link_to "Contact", contact_path %></li>
                    <li class='text-center small-3 column'><%= link_to "News", news_path %></li>
                    <li class='text-center small-3 column'><%= link_to "Help", help_path %></li>
                <% else %>
                    <li class='text-center small-6 column'><%= link_to "About", about_path %></li>
                    <li class='text-center small-6 column'><%= link_to "Contact", contact_path %></li>
              <% end %>
              </div>
            </ul>
        </section>
  </nav>

</footer>

app/views/layouts/_google_analytics.html.erb
<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-48567523-1']);
    _gaq.push(['_setDomainName', 'ordertrk.com']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

</script>

app/views/layouts/_header.html.erb
<header>
      <div>
          <nav class="top-bar full-width" data-topbar>
            <div class='small-12 medium-12 large-12'>
              <section class="top-bar-section">
                  <div class='small-8 medium-6 large-6 columns'>
                    <ul class="left">
                      <li class="vertical-center-align logo title">
                        <%= link_to logo_small, root_path %>
                      </li>
                    </ul>

                    <ul class="title-area hide-for-small-only">
                      <li class="name">
                        <h1><%= link_to "Order Tracking", root_path, :class => 'vertical-center-align' %></h1>
                      </li>
                    </ul>
                    <% if signed_in? %>
                    <ul class="title-area hide-for-small-only">
                        <%= link_to 'NEW! Chrome extenstion!', chrome_ext_path, :class => "button notice", :target => "_blank" %>
                    </ul>
                    <% end %>
                  </div>

                  <div class='small-4 medium-6 large-6 columns'>

                      <!-- Right Nav Section -->
                      <ul class="right">

                        <% if signed_in? %>

                            <li class="has-dropdown not-click hide-for-small-only">
                              <ul>
                              <%= gravatar_for @user, :size => 40 %>
                              <%= link_to current_user.name, user_path(current_user) %>
                              </ul>
                              <ul class="dropdown">

                                <li class='hide-for-small-only settings'><%= link_to "Settings", edit_user_path(current_user) %></li>

                                <li class='hide-for-small-only archive'><%= link_to "Archive", archive_user_path(current_user) %></li>
                                
                                <% if current_user.is_admin? %>
                                    <li class="hide-for-small-only "><%= link_to "Users", users_path %></li>
                                <% end %>

                                <li class='hide-for-small-only'><%= link_to "Bookmarklet", bookmarklet_explain_path  %></li>

                                <li class='signout'><%= link_to "Sign out", signout_path(current_user) %></li>
                              </ul>
                            </li>

                            <li class='show-for-small-only signout'><%= link_to "Sign out", signout_path(current_user) %></li>

                        <% else %>
                            <div class='small-12'>
                                <li><%= link_to "Sign in", signin_path %></li>
                            </div>
                        <% end %>
                      </ul>

                  </div>
              </section>
            </div>
          </nav>
        </div>

</header>

app/views/layouts/_share_this_body_scripts.html.erb
<meta property="og:title" content="Order Tracking - Organize your orders!" />
<meta property="og:type" content="Productivity tool" />
<meta property="og:url" content="http://www.ordertrk.com" />
<meta property="og:image" content="http://www.ordertrk.com/assets/OrderTrackingLogo.png" />
<meta property="og:description" content="Order Tracking is a service that allow you to organize your orders information in one centralized, convenient place. easy to manage from your desktop, tablet or mobile!" />
<meta property="og:site_name" content="Order Tracking" />
<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="https://ws.sharethis.com/button/buttons.js"></script>
<script type="text/javascript" src="https://ss.sharethis.com/loader.js"></script>


<script type="text/javascript">stLight.options({publisher: "802eaf10-560e-4396-84e1-1b5336f0f013", doNotHash: false, doNotCopy: false, hashAddressBar: false, shorten: false});</script>
<script>
    var options={ "publisher": "802eaf10-560e-4396-84e1-1b5336f0f013", "position": "right", "ad": { "visible": false, "openDelay": 5, "closeDelay": 0}, "chicklets": { "items": ["facebook", "googleplus", "twitter", "pinterest", "delicious", "email", "sharethis"]}};
    var st_hover_widget = new sharethis.widgets.hoverbuttons(options);
</script>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<!--<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>-->
<!--<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>-->
<!--[if lt IE 8]>
<%= stylesheet_link_tag 'blueprint/ie' %>
<%= stylesheet_link_tag 'general_enclosed_foundicons_ie7' %>
<![endif]-->
<%= stylesheet_link_tag 'stylesheets/general_enclosed_foundicons' %>
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= stylesheet_link_tag 'application' %>

app/views/layouts/_tab_bar.html.erb
<!-- show-for-small-only-->
<nav class="tab-bar">
  <section class="left-small">
    <a class="left-off-canvas-toggle menu-icon" ><span></span></a>
  </section>

  <section class="middle tab-bar-section">
    <a href="<%= root_path %>"><h3><span><%= logo_small %></span><span class="title">  Order Tracking</span></h3></a>

  </section>
</nav>

<aside class="left-off-canvas-menu">
  <ul class="off-canvas-list">
    <% if signed_in? %>
        <li><label><%= link_to "Main", user_path(current_user) %></label></li>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
        <li><%= link_to "Archive", archive_user_path(current_user) %></li>
        <li><%= link_to "Sign out", signout_path(current_user) %></li>
    <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
    <% end %>
  </ul>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" ng-app="ordertracking">
  <head>
    <%= favicon_link_tag %>
	<title><%= title %></title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <meta name="description" content="Can't track your orders ANYMORE? forgot what you've ordered and when?
    USE Order Tracking! take control over your orders and arrange all of them in one place!"/>
    <meta name="keywords" content="order tracking, ordertrk, order, orders tracking, parcel tracking,
    shipment tracking, order track, track orders, organize orders, orders organizing"/>

    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0-rc.5/angular.min.js" if Rails.env == 'production' %>
    <%= javascript_include_tag "js/angular.min" if Rails.env == 'development' %>
    <%= javascript_include_tag "js/angular-main.js" %>

    <%= render 'layouts/google_analytics' if Rails.env == 'production' %>
  </head>
  <body>
  <!--[if lte IE 9]>
    <div class="broswer-not-supported center">
        <h1>
            This Browser is not supported<br /><hr>
        </h1>

        <h3>
            Please open the site with more modern browser<br />
            and have better user experience!
        </h3>
        <h3>
        <table align=center>
            <tr>
                <td>
                    <a href="http://www.mozilla.org/en-US/firefox/new" target="_blank"><%= image_tag("Firefox-icon.png", :alt => "Download Firefox", :class => "browser_image") %></a>
                </td>
                <td>
                    <a href="http://www.chrome.com" target="_blank"><%= image_tag("chrome3D-icon.jpg", :alt => "Download Chrome", :class => "browser_image") %></a>
                </td>
            </tr>
            <tr>
                <td>
                    Firefox
                </td>
                <td>
                    Chrome
                </td>
            </tr>
        </table>
        </h3>
    </div>
  <![endif]-->

  <!--[if !IE]> -->
  <div class="wrapper">
    <div class="container">
      <div class="off-canvas-wrap" data-offcanvas>
        <div class="inner-wrap">
            <!--for small screens-->
            <div class='show-for-small-only'>
              <%= render 'layouts/tab_bar' %>
            </div>

            <!--for medium & up if touch-->
            <div class='show-for-medium-up'><div class='show-for-touch'>
              <%= render 'layouts/tab_bar' %>
            </div></div>

            <section class='main-section'>

              <div class='hide-for-touch'><div class='hide-for-small'>
                <%= render 'layouts/header' %>
              </div></div>

              <section class="round">
                <div class="row" align="center">
                  <% flash.each do  |key, value| %>

                    <% altkey = (key == :error) ? :alert : key %>
                    <div class="flash <%= altkey %> alert-box radius small-6">
                      <%= value %>
                    </div>
                  <% end %>
                </div>
            
                <%= yield %>
            
              </section>
            </section>
          <a class="exit-off-canvas"></a>
        </div>
      </div>
    </div>
    <div class="push"></div>
  </div>
  <div class="footer">
    <%= debug(params) if Rails.env.development? %>
    <p class='text-center copyrights'>   <%= "\xC2\xA9".force_encoding('UTF-8') %> Copyright 2012-<%= Date.current.year %> Order Tracking</p>
    <%= render 'layouts/footer' %>
  </div>

  <div class="hide-for-small">
    <%= render 'layouts/share_this_body_scripts' %>
  </div>
  <![endif]-->
  </body>
</html>

app/views/layouts/lightbox.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
      <%= favicon_link_tag %>
      <title><%= title %></title>
      <%= csrf_meta_tags %>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />

      <meta name="description" content="Can't track your orders ANYMORE? forgot what you've ordered and when?
        USE Order Tracking! take control over your orders and arrange all of them in one place!"/>
      <meta name="keywords" content="order tracking, ordertrk, order, orders tracking, parcel tracking,
        shipment tracking, order track, track orders, organize orders, orders organizing"/>

      <% if @source == "bookmarklet" %>
        <%= stylesheet_link_tag 'stylesheets/lightbox' %>
      <% else %>
        <%= stylesheet_link_tag 'stylesheets/lightbox_chrome' %>
      <% end %>
      <%= stylesheet_link_tag 'application' %>
      <%= stylesheet_link_tag 'custom', :media => 'screen' %>

      <%= javascript_include_tag "vendor/modernizr" %>
      <%= javascript_include_tag "application" %>

      <%= render 'layouts/google_analytics' if Rails.env == 'production' %>
    </head>
    <body>
        <div id="light" class="white_content">
          <%= yield %>
        </div>
        <div id="fade" class="black_overlay"></div>
    </body>
</html>